# image:
#   file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - name: Rails Server
    init: >
      bundle install &&
      yarn install &&
      rails db:create &&
      rails db:migrate &&
      gp sync-done bundle_migration_init
    command: >
      rails server -b 0.0.0.0
  - name: Tests
    init: gp sync-await bundle_migration_init
    command: >
      bundle exec rspec spec

github:
  prebuilds:
    addBadge: true
