image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
      bundle install &&
      yarn install &&
      rails db:create &&
      rails db:migrate
    command: >
      rails server -b 0.0.0.0
